version: '3.9'

volumes:
  logs:
    driver: local

services:
  db:
    container_name: finder_db
    image: mariadb:10.4
    volumes:
      - ./db-fixtures:/db-fixtures:rw
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
  phpmyadmin:
    container_name: finder_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      TZ: America/Sao_Paulo
      PMA_HOST: finder_db
    ports:
      - 8080:80
    depends_on:
      - db
  finder_api:
    tty: true
    container_name: finder_api_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8089:8089"
    depends_on:
      - db